### ISSUE TITLE
Sites Not Syncing

### ISSUE THREAD

**Issue by theSoberSobber** [maurocasas/fastindex#4]
- I have added Service Account to credentials in fast index
- I have added that service account as owner in the property I wanna index
- I have tried syncing the site from the sync site but it just won't show up

![image](https://github.com/user-attachments/assets/7c93f1f1-61bd-4dde-9b3d-94c5c4e2327c)
![image](https://github.com/user-attachments/assets/b7fbdf75-40a3-4454-bb81-f7136366ca9f)
![image](https://github.com/user-attachments/assets/07d9f15c-8885-4511-9108-70505af9d766)

Are there any logs I could see/provide for debugging purposes? I used the composer method to get it up on my server.

**Comment by maurocasas** [comment]
Hey! Thanks for your issue report.
I'm currently close to releasing a new version.

I forgot to add in the documentation you need to have the queue worker running, I'm trying to mitigate this!

**Comment by akshayrathodar** [comment]
Let me know once you finish with your changes. facing same issue @maurocasas .

**Comment by maurocasas** [comment]
> Let me know once you finish with your changes. facing same issue @maurocasas .

@theSoberSobber 

Bad news guys. Google killed Indexing API due to service abuse. 

I'm deprecating the project.

**Comment by theSoberSobber** [comment]
darn man, well atleast you probably learnt a lot building this!
